before_script:
      - psql -c "CREATE USER coxjc WITH PASSWORD '';" -U postgres
      - psql -c "create database ressit_test;" -U postgres
      - psql -c "alter database ressit_test owner to coxjc;"
language: ruby
rvm: 
    - 2.3.3
